### ISSUE TITLE
Cashify 5.0+ Breaking Changes - Node.js v17.2.0 ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by talkquazi** [xxczaki/cashify#20]
Breaking changes to version 5.0+ of cashify has the following breaking changes that you did not mention in your Readme.

`const { Cashify } = require('cashify');
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module E:\Repos\arbitrage.club\amazonProfit\node_modules\cashify\dist\index.js from E:\Repos\arbitrage.club\amazonProfit\lib\currency.js not supported.
Instead change the require of index.js in E:\Repos\arbitrage.club\amazonProfit\lib\currency.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (E:\Repos\arbitrage.club\amazonProfit\lib\currency.js:1:21)
    at Object.<anonymous> (E:\Repos\arbitrage.club\amazonProfit\lib\amazonProfit.js:32:18)
    at E:\Repos\arbitrage.club\amazonProfit\server.js:64:26
    at Object.init (E:\Repos\arbitrage.club\amazonProfit\lib\ssl.js:65:7)
    at E:\Repos\arbitrage.club\amazonProfit\server.js:50:7
    at E:\Repos\arbitrage.club\amazonProfit\node_modules\entourage\lib\entourage.js:126:9
    at wrapper (E:\Repos\arbitrage.club\amazonProfit\node_modules\async\dist\async.js:271:20)
    at iteratorCallback (E:\Repos\arbitrage.club\amazonProfit\node_modules\async\dist\async.js:501:17)
    at E:\Repos\arbitrage.club\amazonProfit\node_modules\async\dist\async.js:327:20
    at E:\Repos\arbitrage.club\amazonProfit\node_modules\entourage\lib\entourage.js:117:11
    at E:\Repos\arbitrage.club\amazonProfit\node_modules\async\dist\async.js:2557:44
    at eachOfArrayLike (E:\Repos\arbitrage.club\amazonProfit\node_modules\async\dist\async.js:506:13)
    at eachOf (E:\Repos\arbitrage.club\amazonProfit\node_modules\async\dist\async.js:626:16)
    at awaitable (E:\Repos\arbitrage.club\amazonProfit\node_modules\async\dist\async.js:211:32)
    at Object.eachLimit (E:\Repos\arbitrage.club\amazonProfit\node_modules\async\dist\async.js:2660:16)
    at Object.awaitable (E:\Repos\arbitrage.club\amazonProfit\node_modules\async\dist\async.js:211:32)
    at E:\Repos\arbitrage.club\amazonProfit\node_modules\entourage\lib\entourage.js:100:11
    at f (E:\Repos\arbitrage.club\amazonProfit\node_modules\once\once.js:25:25)
    at Glob.<anonymous> (E:\Repos\arbitrage.club\amazonProfit\node_modules\entourage\node_modules\glob\glob.js:148:7)
    at Glob.emit (node:events:390:28)
    at Glob._finish (E:\Repos\arbitrage.club\amazonProfit\node_modules\entourage\node_modules\glob\glob.js:194:8)
    at done (E:\Repos\arbitrage.club\amazonProfit\node_modules\entourage\node_modules\glob\glob.js:179:14)
    at Glob._processSimple2 (E:\Repos\arbitrage.club\amazonProfit\node_modules\entourage\node_modules\glob\glob.js:703:3)
    at E:\Repos\arbitrage.club\amazonProfit\node_modules\entourage\node_modules\glob\glob.js:673:10
    at Glob._stat2 (E:\Repos\arbitrage.club\amazonProfit\node_modules\entourage\node_modules\glob\glob.js:786:10)
    at lstatcb_ (E:\Repos\arbitrage.club\amazonProfit\node_modules\entourage\node_modules\glob\glob.js:761:12)
    at RES (E:\Repos\arbitrage.club\amazonProfit\node_modules\inflight\inflight.js:31:16)
    at f (E:\Repos\arbitrage.club\amazonProfit\node_modules\once\once.js:25:25)
    at FSReqCallback.oncomplete (node:fs:199:5) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v17.2.0`

**Comment by xxczaki** [comment]
I mentioned the transition to ESM both in [the changelog](https://github.com/xxczaki/cashify/releases/tag/3.0.0) and [README](https://github.com/xxczaki/cashify#install).

**Comment by talkquazi** [comment]
The standard thing to do is to put a header near the top of your README that says **BREAKING CHANGES** in bold and explain the change there. 

Furthermore, your changes break the module in NodeJS. Out of thousands of modules that I have used in my years of using NodeJS this is the first module to completely break the loading mechanism using require. This is also the first module to not specifically announce **BREAKING CHANGES** at the top of the README.

Your changes also makes this section of your README inaccurate https://github.com/xxczaki/cashify#migrating-from-moneyjs aka a lie.

**Suggestion**: Make require work by allowing an async module loader so import is not forced as majority of people using Node are still using require and do not want to asynchronously setup a workaround to require a module.

PS: Looking at your download statistics based on version it is pretty clear you have disenfranchised many people with these breaking changes.

https://www.npmjs.com/package/cashify <-- click versions tab at the top
`Version
Downloads (Last 7 Days)

    Published

3.0.1
30

    20 hours ago

3.0.0
102

    6 days ago

2.5.0
2,790

    a year ago

2.4.4
16

    a year ago

2.4.3
239

    a year ago`

**Comment by d2xdt2** [comment]
I am maintaining an ES2017 fork of this package at https://www.npmjs.com/package/cashify-es2017 , which means it can be used as any other package.
